app/users/models.py
from app.users import constants as USER
from flask import Flask

from flask.ext.sqlalchemy import SQLAlchemy
app = Flask(__name__)
db = SQLAlchemy(app)


class User(db.Model):

    __tablename__ = 'users_user'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(120))
    role = db.Column(db.SmallInteger, default=USER.USER)
    status = db.Column(db.SmallInteger, default=USER.NEW)
    user_data = relationship("UserData",
    __tablename__ = 'user_data'
    id = db.Column(db.Integer, primary_key=True)
    balance = db.Column(db.Integer, default=0)
    

def __init__(self, name=None, email=None, password=None):
  self.name = name
  self.email = email
  self.password = password

def getStatus(self):
  return USER.STATUS[self.status]

def getRole(self):
  return USER.ROLE[self.role]

def __repr__(self):
  return '<User %r>' % (self.name)

app/users/forms.py
from flask.ext.wtf import Form, RecaptchaField
from wtforms import TextField, PasswordField, BooleanField
from wtforms.validators import Required, EqualTo, Email, NumberRange

class LoginForm(Form):
  email = TextField('Email address', [Required(), Email()])
  password = PasswordField('Password', [Required()])

class RegisterForm(Form):
  name = TextField([Required()])
  email = TextField('Email address', [Required(), Email()])
  password = PasswordField('Password', [Required()])
  confirm = PasswordField('Repeat Password', [
      Required(),
      EqualTo('password', message='Passwords must match')
      ])
  accept_tos = BooleanField('I accept the TOS', [])
  accno = TextField()
  #recaptcha = RecaptchaField()
  
class ItemForm(Form):
  iname = TextField('Item Name', [Required()])
  idesc = TextField('Item Description')
  icost = TextField('Item Cost')
  ilink = TextField('Item Link')
  ipriority = TextField('Item Priority',[NumberRange(min=0)])
  iminbal = TextField('Minimum Balance Required to purchase',[Required(), NumberRange(min=0)])

app/users/__init__.py
from flask import Flask, render_template

app = Flask(__name__)

@app.route("/")
def main():
	return "hello world"
@app.errorhandler(404)
def not_found(error):
        return render_template('404.html'), 404


    
if __name__ == "__main__":
	app.run(debug=True)

app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for,Flask
from werkzeug import check_password_hash, generate_password_hash
from sqlalchemy import create_engine, MetaData
from sqlalchemy import Table, Column, Integer, String
from app import db
from app.users.forms import RegisterForm, LoginForm, ItemForm
#from app.users.models import User
from app import User, UserData
from app.users.decorators import requires_login
from app.capitalData import *

mod = Blueprint('users', __name__, url_prefix='/users')
#engine = create_engine('sqlite:////app.db')
#metadata = MetaData()
#metadata.create_all(bind=engine)

@mod.route('/me/', methods=['GET', 'POST'])
@requires_login
def home():
  id=0
  balance_current=get_Balance(id)
  print "home balance is " + str(balance_current)
  myid= session['user_id']
  form = LoginForm(request.form)
  user = User.query.filter_by(id=myid).update(dict(balance=balance_current))
  db.session.commit() 
  
  r=UserData.query.filter_by(id=myid).all()
  item_names=[]
  item_descs=[]
  item_costs=[]
  item_links=[]
  item_prioritys=[]
  item_minbals=[]
  item_ids=[]
  global count
  count=0
  for items in r:
    item_ids.append(items.item_id)
    item_names.append(items.item_name)
    if items.item_desc==' ':
      item.descs.append("No Description")
    else:  
      item_descs.append(items.item_desc)
    item_costs.append(items.item_cost)
    item_links.append(items.item_link)
    item_prioritys.append(items.item_priority)
    item_minbals.append(items.item_minbal)
    count=count+1
  print item_ids
  print item_names
  print item_descs
  print item_costs
  print item_links
  print item_prioritys
  print item_minbals
			    
			    
  return render_template("users/profile.html", user=g.user,count=count,item_names=item_names,item_descs=item_descs,item_costs=item_costs,item_links=item_links,item_prioritys=item_prioritys,item_minbals=item_minbals, item_ids=item_ids)
  
@mod.route('/me/add_item', methods=['GET', 'POST'])  
@requires_login    
def add_item():
  myid= session['user_id']
  form3 = ItemForm(request.form)
  if request.method == "POST" and form3.validate_on_submit():
    flash("Success")
    useritem = UserData(id=myid, item_name=form3.iname.data,item_desc=form3.idesc.data, item_cost=form3.icost.data,item_link=form3.ilink.data,item_priority=form3.ipriority.data, item_minbal=form3.iminbal.data)
    # Insert the record in our database and commit it
    db.session.add(useritem)
    db.session.commit()
    print "Item added successfully"
  return render_template("users/add_item.html", user=g.user,form3=form3)

@mod.route('/me/delete_item/<id>', methods=['GET', 'POST'])  
@requires_login    
def delete_item(id):
  user = UserData.query.get(id)
  db.session.delete(user)
  db.session.commit()
  print "Item successfully deleted"
  return redirect(url_for('users.home'))

@mod.before_request
def before_request():
     # "pull user's profile from the database before every request are treated"
  g.user = None
  if 'user_id' in session:
    g.user = User.query.get(session['user_id'])

@mod.route('/login/', methods=['GET', 'POST'])
def login():
#  Login form
  form = LoginForm(request.form)
      # make sure data are valid, but doesn't validate password is right
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
        # we use werzeug to validate user's password
    if user and check_password_hash(user.password, form.password.data):
          # the session can't be modified as it's signed, 
          # it's a safe place to store the user id
      session['user_id'] = user.id
      flash('Welcome %s' % user.name)
      #window.top.location.href= url_for('users.home')
      return redirect(url_for('users.home'))
    flash('Wrong email or password', 'error-message')
    
  return render_template("users/login.html", form=form)

@mod.route('/register/', methods=['GET', 'POST'])
def register():
    #  Registration Form
  form = RegisterForm(request.form)
  if form.validate_on_submit():
        # create an user instance not yet stored in the database
    user = User(name=form.name.data, email=form.email.data, \
        password=generate_password_hash(form.password.data))
        # Insert the record in our database and commit it
    db.session.add(user)
    db.session.commit()

        # Log the user in, as he now has an id
    session['user_id'] = user.id

        # flash will display a message to the user
    flash('Thanks for registering')
        # redirect user to the 'home' method of the user module.
    return redirect(url_for('users.home'))
  return render_template("users/register.html", form=form)

app/templates/users/add_item.html
{% extends "base.html" %}
    {% block content %}
      {% from "forms/macros.html" import render_field %}
     
      <form method="POST" action="/users/me/add_item" class="form3">
       <div class="input-field">
        {{ form3.csrf_token }}
        {{ render_field(form3.iname,id="iname", class="input text", placeholder='Item Name', type="text") }}
        {{ render_field(form3.idesc, class="input text", placeholder='Item Description') }}
        {{ render_field(form3.icost, class="input text", placeholder='Item Cost') }}
        {{ render_field(form3.ilink, class="input text", placeholder='Item Link') }}
        {{ render_field(form3.ipriority, class="input text", placeholder='Item Priority') }}
        {{ render_field(form3.iminbal, class="input text", placeholder='Minimum Balance Required to purchase item') }}
        <input type="submit" value="Add Item" class="btn green">
      </form><br/><br/>
      <a class="btn green" href="{{ url_for('users.home') }}">Home</a>
      </div>
    {% endblock %}

app/templates/users/items.html
<html>
  <head>
    <title></title>
    <meta content="">
    <style></style>
  </head>
  <body></body>
</html>

app/templates/users/login.html
    {% extends "base.html" %}
    {% block content %}
      {% from "forms/macros.html" import render_field %}
      <form method="POST" action="." class="form">
        {{ form.csrf_token }}
        {{ render_field(form.email, class="input text",placeholder='E-mail Address') }}
        {{ render_field(form.password, class="input text", placeholder='Password') }}
        <input type="submit" value="Login" class="btn green">
      </form>
    {% endblock %}

app/templates/users/profile.html
   {% extends "base.html" %}
   {% block content %}

       <script src="/static/jquery-2.1.3.min.js"></script>
    <script src="/static/materialize.js"></script>
      <script>
  $(document).ready(function() {
  $('.modal-trigger').leanModal();
//   $('.parallax').parallax();
//   Waves.displayEffect();
   $('select').not('.disabled').material_select();
});
</script>

       <div id="index-banner" class="container">
        <div class="section">
            <div class="container">
     <h3>Name: {{ user.name }}<br/>

   Total balance: {{ user.balance }}$
 </h3>
 <h4>Items</h4>
 <hr/>
 {%for x in range(0,count)%}
 Name:<a href={{item_links[x]}}>{{item_names[x]}}</a> &nbsp; &nbsp; Priority level:{{item_prioritys[x]}}<br/>
 Description: {{item_descs[x]}}<br/>
 Price: {{item_costs[x]}} &nbsp; &nbsp; Minimum Balance required: {{item_minbals[x]}}<br/>
 <a href="/users/me/delete_item/{{item_ids[x]}}">Delete</a>
 <hr/>
 
 {%endfor%}
   <a href="add_item" class="btn-floating btn-large waves-effect waves-light red right"><i class="material-icons">add</i></a>

  
 </div>
    {% endblock %}

app/templates/users/register.html
{% extends "base.html" %}
    {% block content %}
      {% from "forms/macros.html" import render_field %}
     
      <form method="POST" action="." class="form-group form col row s12"">
       <div class="input-field col s12">
        {{ form.csrf_token }}
        {{ render_field(form.name,id="name", class="form-control", placeholder='Name', type="text") }}
        {{ render_field(form.email, class="input text", placeholder='E-mail Address') }}
        {{ render_field(form.password, class="input text", placeholder='Password') }}
        {{ render_field(form.confirm, class="input text", placeholder='Confirm Password') }}
        <input type="submit" value="Register" class="btn green">
      </form>
      <a href="{{ url_for('users.login') }}">Login</a>
      </div>
    {% endblock %}
   